# Generated by Django 6.0.3 on 2026-03-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
