# Generated by Django 6.0.3 on 2026-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_reservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity_adults',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity_children',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='total_capacity',
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
    ]
