# Generated by Django 6.0.3 on 2026-04-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_capacity_adults_room_capacity_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='total_capacity',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
