# Generated by Django 6.0.3 on 2026-04-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_total_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
