# Generated by Copilot for service selection flow

from decimal import Decimal

from django.db import migrations, models


def create_default_services(apps, schema_editor):
    Service = apps.get_model('rooms', 'Service')

    default_services = [
        {
            'name': 'Airport transfer',
            'slug': 'airport-transfer',
            'description': 'Đưa đón sân bay an toàn, đúng giờ và tiện lợi cho khách lưu trú.',
            'price': Decimal('250000.00'),
            'image_url': '/static/images/f-1.png',
            'order': 1,
        },
        {
            'name': 'All inclusive',
            'slug': 'all-inclusive',
            'description': 'Gói trọn tiện ích dành cho khách muốn tận hưởng kỳ nghỉ không lo phát sinh.',
            'price': Decimal('450000.00'),
            'image_url': '/static/images/f-2.png',
            'order': 2,
        },
        {
            'name': 'Air-conditioned',
            'slug': 'air-conditioned',
            'description': 'Nâng cấp phòng với dịch vụ điều hòa mát mẻ và thoải mái suốt thời gian lưu trú.',
            'price': Decimal('100000.00'),
            'image_url': '/static/images/f-3.png',
            'order': 3,
        },
        {
            'name': 'Under protection',
            'slug': 'under-protection',
            'description': 'Dịch vụ hỗ trợ an ninh và bảo vệ riêng để tăng cảm giác yên tâm cho khách.',
            'price': Decimal('150000.00'),
            'image_url': '/static/images/f-4.png',
            'order': 4,
        },
    ]

    for service_data in default_services:
        Service.objects.get_or_create(
            slug=service_data['slug'],
            defaults={key: value for key, value in service_data.items() if key != 'slug'},
        )


def remove_default_services(apps, schema_editor):
    Service = apps.get_model('rooms', 'Service')
    Service.objects.filter(slug__in=[
        'airport-transfer',
        'all-inclusive',
        'air-conditioned',
        'under-protection',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_reservation_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='selected_services',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='rooms.service'),
        ),
        migrations.RunPython(create_default_services, remove_default_services),
    ]
