# Generated by Copilot to support deposit/balance and checkout damage billing.

from decimal import Decimal

from django.db import migrations, models


def backfill_reservation_financials(apps, schema_editor):
    Reservation = apps.get_model('rooms', 'Reservation')

    for reservation in Reservation.objects.all():
        total = reservation.total or Decimal('0.00')
        deposit_percentage = reservation.deposit_percentage or Decimal('30.00')
        deposit_amount = (total * deposit_percentage) / Decimal('100')
        balance_due = total - deposit_amount
        damage_fee = reservation.damage_fee or Decimal('0.00')
        reservation.deposit_amount = deposit_amount
        reservation.balance_due = balance_due
        reservation.final_total = total + damage_fee
        reservation.save(update_fields=['deposit_amount', 'balance_due', 'final_total'])


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_reservation_checkout_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='damage_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='damage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='damage_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RunPython(backfill_reservation_financials, migrations.RunPython.noop),
    ]