# Generated by Django 4.2 on 2026-05-01 23:11

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_reservation_invoice_notified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('pay_on_arrival', 'Cash on Arrival'), ('cash', 'Cash'), ('momo_qr', 'MoMo QR'), ('upi', 'UPI'), ('cards', 'Cards')], default='pay_on_arrival', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rooms.models.room_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to=rooms.models.room_gallery_upload_path),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rooms.models.service_image_upload_path),
        ),
    ]
