# Generated by Django 6.0.3 on 2026-05-02 12:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_alter_reservation_payment_method_alter_room_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='actual_check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='early_checkin_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='early_checkin_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
