# Generated by Django 6.0.3 on 2026-05-02 12:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_reservation_actual_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='actual_check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='balance_paid_at_checkin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_paid_via_qr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='early_checkout_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='early_checkout_refund',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
