# Generated by Django 6.0.3 on 2026-05-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_reservation_actual_check_out_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('momo_qr', 'Chuyển khoản MoMo'), ('cards', 'Quẹt thẻ')], default='cash', max_length=20),
        ),
    ]
