# Generated by Django 6.0.3 on 2026-05-03 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_alter_reservation_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deposit_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/deposit_receipts/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
