# Generated by Django 6.0.3 on 2026-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_reservation_canceled_at_reservation_canceled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
