# Generated by Django 5.1.2 on 2026-03-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Nhập class FontAwesome (vd: fas fa-wifi)', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.service'),
        ),
    ]
